---
abstract: unknown
author:
  - 'Peter John Acklam <pjacklam@gmail.com>'
build_requires:
  Test::More: '0.82'
configure_requires:
  ExtUtils::MakeMaker: '6.58'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.38, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-BigInt-GMP
no_index:
  directory:
    - t
    - inc
requires:
  Math::BigInt: '1.999817'
  XSLoader: '0.02'
  perl: '5.006001'
resources:
  repository: https://github.com/pjacklam/p5-Math-BigInt-GMP.git
version: '1.6007'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
